esphome:
  name: color-display
  friendly_name: Color Display
  platformio_options:
    board_build.arduino.memory_type: qio_opi
    board_build.f_cpu: 240000000L
    board_build.f_flash: 80000000L

external_components:
  source:
    type: git
    url: https://github.com/DavBfr/esphome_components

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

display:
  - platform: tft_gpio
    lambda: |-
      it.fill(Color(0, 0, 255));
      it.print(it.get_width() / 2, it.get_height() / 2, id(my_font), Color(255, 0, 0), TextAlign::CENTER, "Hello World!");

font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 60
